name: 'Service sync deploy actions'
description: 'Service sync deploy actions'
inputs:
  argocd-server:
    required: true
  argocd-auth-token:
    required: true
  argocd-app:
    required: true
  cf-access-client-id:
    required: true
  cf-access-client-secret:
    required: true
runs:
  using: "composite"
  steps:
    - name: Env Config
      run: |
        echo "ARGOCD_SERVER=${{ inputs.argocd-server }}" >> $GITHUB_ENV
        echo "ARGOCD_AUTH_TOKEN=${{ inputs.argocd-auth-token }}" >> $GITHUB_ENV
    - name: Sync
      run: |
        curl -sSL -o /usr/local/bin/argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64 -H "CF-Access-Client-Id:${{ inputs.cf-access-client-id }}" -H "CF-Access-Client-Secret:${{ inputs.cf-access-client-secret }}"
        chmod +x /usr/local/bin/argocd
        argocd app sync ${{ inputs.argocd-app }} --grpc-web -H "CF-Access-Client-Id:${{ inputs.cf-access-client-id }}" -H "CF-Access-Client-Secret:${{ inputs.cf-access-client-secret }}" --async
        argocd app wait ${{ inputs.argocd-app }} --sync --health --operation --grpc-web -H "CF-Access-Client-Id:${{ inputs.cf-access-client-id }}" -H "CF-Access-Client-Secret:${{ inputs.cf-access-client-secret }}" --timeout 600
      shell: bash